
printf("<html>");
printf("  <head>");
printf("    <!-- regular meta stuff -->");
printf("    <meta content='text/html;charset=utf-8' http-equiv='Content-Type'>");
printf("    <meta content='utf-8' http-equiv='encoding'>");
printf("    <!-- meta that stops the website hmtl itself getting cached -->");
printf("    <meta http-equiv='Cache-Control' content='no-cache, no-store, must-revalidate' />");
printf("    <meta http-equiv='Pragma' content='no-cache' />");
printf("    <meta http-equiv='Expires' content='0' />");
printf("    <style>");
printf("      /* styles that start with a dot are classes. these can be applied to multiple elements */");
printf("      .control {");
printf("        border: 1px solid #000000;");
printf("        border-radius: 20px;");
printf("        display: inline-block;");
printf("        font-size: 400%;");
printf("        height: 78px;");
printf("        margin: 20px;");
printf("        padding: 20px;");
printf("        position: absolute;");
printf("        text-align: center;");
printf("        width: 150px;");
printf("      }");
printf("      /* styles that start with a # are IDs. these refer to one specific element  */");
printf("      #beep {");
printf("        background-color: rgb(194,194,255);");
printf("        left: 100px;");
printf("        top: 100px;");
printf("      }");
printf("      #boop {");
printf("        background-color: rgb(255,192,255);");
printf("        left: 600px;");
printf("        top: 100px;");
printf("      }");
printf("    </style>");
printf("  </head>");
printf("  <body>");
printf("    <!-- these are the divs that are used as buttons on the page the have both an id and a class-->");
printf("    <div id = 'beep' class = 'control'>beep</div>");
printf("    <div id = 'boop' class = 'control'>boop</div>");
printf("    <script>");
printf("      // this does the GET request");
printf("      const httpGet = (");
printf("        mouseEvent,");
printf("      ) => {");
printf("        // find the element that is under the mouse cursor");
printf("        const selectedElement = document.elementFromPoint(mouseEvent.x, mouseEvent.y);");
printf("        // continue if element is found");
printf("        if (selectedElement !== null) {");
printf("          // pull the url string out of the element");
printf("          const urlString = selectedElement.dataset.url;");
printf("          // contine if the url string was found");
printf("          if (urlString !== undefined) {");
printf("            // use fetch to GET the full url, without caching the result");
printf("            fetch(`https://blackarm0815.com/api/${urlString}`, {cache: 'no-cache'})");
printf("              // wait for the response and log it to the console");
printf("              .then((response) => console.log(response));");
printf("          }");
printf("        }");
printf("      };");
printf("      // add event listeners to the divs and store their url strings");
printf("      const eventListeners = () => {");
printf("        let divElement;");
printf("        // find the element");
printf("        divElement = document.getElementById('beep');");
printf("        // continue if it is found");
printf("        if (divElement !== null) {");
printf("          // add the event listener");
printf("          divElement.addEventListener('click', httpGet);");
printf("          // store the url string in the element");
printf("          divElement.dataset.url = 'beep';");
printf("        }");
printf("        // find the element");
printf("        divElement = document.getElementById('boop');");
printf("        // continue if it is found");
printf("        if (divElement !== null) {");
printf("          // add the event listener");
printf("          divElement.addEventListener('click', httpGet);");
printf("          // store the url string in the element");
printf("          divElement.dataset.url = 'boop';");
printf("        }");
printf("      };");
printf("      // call the event listener function to set everything up");
printf("      eventListeners();");
printf("    </script>");
printf("  </body>");
printf("</html>");
